# Configuration settings for the GPS NMEA processing program.
# This file contains settings related to the UART communication (port, baudrate) and other operational parameters.

UART:
  port: /dev/ttyUSB0
  baudrate: 9600

GPS_SCAN:
  timeout: 10  # Number of seconds without receiving a valid sentence before assuming an unexpected end of scan or disruption.

NMEA_LOGFILE:
  timestamp_prefix: "t="
  delimiter: ", "
  field_separator: ","
  nmea_type_prefix: "$"
