# Configuration settings for the GPS NMEA processing program.
# This file contains settings related to the UART communication (port, baudrate, parity, etc) and other operational parameters.

UART:
  serial_port: '/dev/ttyUSB0'  #  This can vary based on platform/OS
  baudrate: 9600
  parity: 'N'
  stopbits: 1

NMEA_LOGFILE:
  timestamp_prefix: "t="
  delimiter: ", "
  field_separator: ","
  nmea_type_prefix: "$"
